name: Deploy to ACSWeb

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: os-ucsd/actions/acsweb@0.1.1
      with:
        username: os-ucsd
        password: "${{secrets.password}}"
